version: '3'

services:
  tr-transactions:
    image: tr-transactions
    build:
      context: .
      dockerfile: TrTransactions/TrTransactions/Dockerfile
    depends_on:
      - postgresql.data

  tr-deals:
    image: tr-deals
    build:
      context: .
      dockerfile: TrDeals/TrDeals/Dockerfile

  postgresql.data:
    image: postgres

