version: '3'

services:
  postgresql.data:
    image: postgres

  tr-transactions:
    image: tr-transactions
    build:
      context: .
      dockerfile: TrTransactions/TrTransactions/Dockerfile
    depends_on:
      - postgresql.data

  tr-deals:
    image: tr-deals
    build:
      context: .
      dockerfile: TrDeals/TrDeals/Dockerfile
    depends_on:
      - postgresql.data

  tr-currencies:
    image: tr-currencies
    build:
      context: .
      dockerfile: TrCurrencies/TrCurrencies/Dockerfile
    depends_on:
      - postgresql.data

  tr-webapptest:
    image: tr-webapptest
    build:
      context: .
      dockerfile: TrWebAppTest/TrWebAppTest/Dockerfile

