version: '3'

services:
  trading:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DbConnectionString=${TR_DB:-Host=postgresql.data;Port=5432;Database=tr-transactions;Username=tr-user;Password=postgres1}
    ports:
      - "8005:80"

  postgresql.data:
    environment:
      - POSTGRES_PASSWORD=postgres1
      - POSTGRES_USER=tr-user
    ports:
      - "5433:5432"